#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConstant {
    uint value;
} pc;

layout(set = 0, binding = 0, std430) restrict buffer BufferData {
    uint data[];
} buffer_data;

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= buffer_data.data.length()) {
        return;
    }
    buffer_data.data[index] += pc.value;
}
